### PR TITLE
Move documentation to the Wiki

### PR DESCRIPTION
**Pull request by RobLoach**
Moving documentation [to the wiki](https://github.com/jstransformers/boilerplate/wiki) will allow us to change docs without affecting child projects.

https://github.com/jstransformers/boilerplate/wiki

Perhaps we even turn `jstransformer-boilerplate` into an actual project with working implementations of .render(), .compile(), etc.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
I think that documentation needs to be visible front and centre because it explains what this repo is.

I'm not sure I understand how changing it affects child repos?

**Comment by TimothyGu** [comment]
I believe this commit prevents leaking boilerplate setup instructions to jstransformers. However, I agree with @ForbesLindesay that there should be a link somewhere to the wiki now that it is not on the front page.

**Comment by RobLoach** [comment]
What @TimothyGu said... I've updated it with [A BIG DOCUMENTATION HEADER LINK AT THE TOP](https://github.com/jstransformers/boilerplate/blob/wiki/README.md).

**Comment by ForbesLindesay** [comment]
That still has potential to accidentally leak though?

**Comment by TimothyGu** [comment]
Another way to solve this is by putting the wiki link into the repo description, which hopefully will be hard to miss.

**Comment by ForbesLindesay** [comment]
I can't help but think that all of these options are worse than what we have at the moment.

Currently it's super obvious when you view the readme and super clear that you're expected to remove it before publishing your module.

**Comment by RobLoach** [comment]
> Currently it's super obvious when you view the readme and super clear that you're expected to remove it before publishing your module.

https://github.com/jstransformers/boilerplate/tree/wiki#see-the-boilerplate-wiki-for-usage-instructions

I'd consider a big h1 link pretty obvious. Perhaps we keep minimal listed instructions, but push them forwards to the wiki documentation? Having [the more detailed stuff](https://github.com/jstransformers/boilerplate/wiki) in the wiki does seem appropriate.

What about something like..........

```markdown
# JSTransformer Boilerplate

Use this to create and update transformers.

1. Visit [the Boilerplate Wiki](https://github.com/jstransformers/boilerplate/wiki) on how to use the Boilerplate
2. Remove this top notice from any transformers.

# jstransformer-foo

[...]
```

**Comment by ForbesLindesay** [comment]
That would be fine by me :)

**Pull request closed without merging**
