### PR TITLE
Add Dependencies badge

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by TimothyGu** [comment]
devDependencies too maybe?

**Comment by ForbesLindesay** [comment]
I'd prefer not to have devDependencies.  An out of date devDependency is way too unimportant to bother a user over.

**Comment by ForbesLindesay** [comment]
Do we prefer gemnasium or david-dm?  I have no personal preference.

**Comment by RobLoach** [comment]
I prefer [david-dm](https://david-dm.org), as it doesn't have [a Billing modal behind it](https://gemnasium.com/settings/billing).

**Comment by TimothyGu** [comment]
LGTM.

**Pull request merged**
